# Generated by Django 4.2.27 on 2026-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_options_alter_product_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
