# Generated by Django 4.2.27 on 2026-02-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="breif_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
